const PORT = 3000;

const express = require('express');
const app = express();

const mainRouter = require('./routes/main');
const wordsRouter = require('/routes/main');

//swagger config
const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  apis: ['./routes/*.js'],
};
const specs = swaggerJsdoc(options);
const swaggerUi = require('swagger-ui-express');
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));



app.use(express.json());

app.use('/main', mainRouter);
app.use('/words',wordsRouter);

app.listen(PORT, () => console.log('Server online'));