const PORT = 3000;

const express = require('express');
const app = express();

const mainRouter = require('./routes/main');





const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['./routes/*.js'],
};

const specs = swaggerJsdoc(options);

const swaggerUi = require('swagger-ui-express');
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));





app.use(express.json());

app.use((req, res, next) => {
    //el * todos los dominios son aceptados
    res.header('Access-Control-Allow-Origin', '*');
    next();//imprescindible next para que se ejecute la siguiente 
});


app.use('/main', mainRouter);

app.listen(PORT, () => console.log('Server online'));